version: '3'

services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5455:5432
  app:
    build: .
    volumes:
      - ./rails_app:/rails_app
    ports:
      - 3008:3000
    environment:
      - RAILS_ENV=${RAILS_ENV}
    depends_on:
      - db